apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: northwind
  name: northwind
spec:
  replicas: 1
  selector:
    io.kompose.service: northwind
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: northwind
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: ConnectionStrings__NorthwindDatabase
          value: Server=data-sql;Database=NorthwindTradersDb;User Id=sa;Password=Pass@word
        image: ' '
        name: northwind
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - northwind
      from:
        kind: ImageStreamTag
        name: northwind:latest
    type: ImageChange
status: {}
