apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: northwind
  name: northwind
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: northwind:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
